site_name: Dokkup
theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
 
nav:
  - Getting started: index.md
  - Agent setup: agent-setup.md
  - CLI setup: cli-setup.md

  - Deploying jobs:
     - Inventory: deploying_jobs/inventory.md
     - Job: deploying_jobs/job.md
