site_name: Dokkup
theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
 
nav:
  - Getting started: index.md
  - Agent setup: agent-setup.md
  - CLI setup: cli-setup.md

  - Deploying jobs:
     - Inventory: deploying_jobs/inventory.md
     - Job specification: deploying_jobs/job.md
     - Deploy a job: deploying_jobs/deploy-job.md
  
  - Managing jobs:
     - Update: managing_jobs/update.md
     - Canary update: managing_jobs/canary_update.md
     - Rollback: managing_jobs/rollback.md
     - Scaling: managing_jobs/scaling.md
     - Stop: managing_jobs/stop.md
     - Remove/purge: managing_jobs/remove.md
     - Show job status: managing_jobs/show_status.md

  - Examples:
     - Reverse Proxy & Load Balancing with TLS using Traefik: examples/traefik.md
